Vingaores requisicoes
2020-1-DTool/backend pull request #1
Opened 2020-05-22 02:13 UTC by AlexBTeixeira

Atualização de requisições

Deve ser feita todas as atualizações necessárias na API para receber os dados das coletas de tempos gerados pelo front, um endpoint para receber os tempos da coleta.

Alex Brustolin Teixeira

## Checklist

- ✅ funciona conforme especificação no Postman
- ✅/⚠️/❌/🤷‍♀️ possui testes de unidade/integração associados 
- ✅/⚠️/❌/🤷‍♀️ mantém cobertura de pelo menos 50%
- ⚠️ documentação atualizada (Mudança nos arquivos JSON de exemplo)
- ✅ código dentro dos padrões
- ✅ código sem warnings ou erros de linter
- ❌ adiciona dependências externas (✅/⚠️/❌/🤷‍♀️ aprovadas pelos AGES III)

Legenda:
- ✅: sim (funciona/builda/documentação atualizada/...)
- ⚠️: parcialmente (partes não funcionam/apenas documentação pendente/...)
- ❌: não (não builda/não funciona/não segue padrões/sem documentação/...)
- 🤷‍♀️: não se aplica (não tenho como testar/não modifica arquivos `.js`, então não precisa de linter/...)

## Outras informações

Anexo código de erro em relação a uma Foreign Key (role_activities + executions: tem de ser feita manualmente e depois da chamada ao sync, porque o sequelize não suporta FKs compostas)(https://github.com/sequelize/sequelize/issues/311) 

![image](https://user-images.githubusercontent.com/50891104/82624329-a30c4700-9bb8-11ea-9003-38830ceca86f.png)

Novo JSON
        _________________________________________________________________________________________________
{
	"deviceToken": "qwertyuiopasdfghjklzxcvbnm1234567890",
	"executions": [
		{
			"activityId": 1,
			"roleId": 3,
			"timestamp": "2020-04-04T14:20:37-0300",
			"duration": 97
		},
		{
			"activityId": 2,
			"roleId": 1,
			"timestamp": "2020-04-04T18:00:54-0300",
			"duration": 326
		}
	]
}
      _________________________________________________________________________________________________

2020-05-22 21:51 UTC, biancacamargomachado requested changes

2020-05-22 21:51 UTC, biancacamargomachado commented on src/routes/executions.js
> +          "message": "fields 'deviceToken' and 'executions' are required, and there should be at least one execution"
Esse mensagem não me parece mt relacionada ao if ali de cima, falta atualizar?
Talvez especificando qual está null... ou pelo menos todas as possibilidades na mensagem.

```suggestion
          "message": "fields 'deviceToken' and 'executions' are required, and there should be at least one execution"
```

2020-05-22 21:51 UTC, biancacamargomachado commented on src/services/ExecutionService.js
> +}
Só adicionar uma nova linha no fim do arquivo

```suggestion
}

```

2020-05-22 21:51 UTC, biancacamargomachado commented on src/services/index.js
> +export { default as ExecutionService } from "./ExecutionService"
Só adicionar uma nova linha no fim do arquivo

```suggestion
export { default as ExecutionService } from "./ExecutionService"
```

2020-05-22 21:54 UTC, AlexBTeixeira commented on src/routes/executions.js
> +          "message": "fields 'deviceToken' and 'executions' are required, and there should be at least one execution"
Oi Bianca estava padrão desse jeito no postman, também pensei que era bem genérico, mas procurei seguir a documentação. Devo mudar?

2020-05-23 14:32 UTC, rafaelruwer requested changes
Não comentei sobre alguns warnings do linter, nem sobre formatação. Depois de resolver o que foi comentado, roda um `npm run lint` e ajusta o que ele der de warnings nos arquivos que você mexeu (vai dar em outros arquivos também, mas nesses não precisa mexer).

Depois disso, roda um `npm run format` para ajustar a formatação (vai mudar arquivos que você não mexeu, mas não tem problema, pode commitar junto).

2020-05-23 14:32 UTC, rafaelruwer commented on src/routes/executions.js
> +  router.post("/", authService.middlewares.requireAppAdministration, (req, res) => {
Duas coisas:
- tens de mudar o nível de autenticação para `autenticated`, senão apenas admins poderão fazer e requisição (erro meu em não te avisar pra mudar quando tu tava fazendo, sorry);
- a _arrow function_ tem que ser `async`, porque você precisa esperar salvar no banco (operação assíncrona) pra retornar pro cliente (deixei um comentário na linha 42 também).

```suggestion
  router.post("/", authService.middlewares.authenticated, async (req, res) => {
```

2020-05-23 14:32 UTC, rafaelruwer commented on src/routes/executions.js
> +    for (var item of req.body.executions) {
Warning no linter, trocar `var` por `const`:

```suggestion
    for (const item of req.body.executions) {
```

2020-05-23 14:32 UTC, rafaelruwer commented on src/routes/executions.js
> +      const duration = item.duration
Dá pra simplificar usando _object destructuring_ (além de resolver os warnings do linter):

```suggestion
      const { activityId, roleId, timestamp, duration } = item
```

2020-05-23 14:32 UTC, rafaelruwer commented on src/routes/executions.js
> +          "message": "fields 'deviceToken' and 'executions' are required, and there should be at least one execution"
Bem notado @biancacamargomachado, pode mudar sim @AlexBTeixeira (vou atualizar o Postman também):

```suggestion
          "message": "fields `activityId`, `roleId`, `timestamp` and `duration` are required on all executions"
```

2020-05-23 14:32 UTC, rafaelruwer commented on src/routes/executions.js
> +    executionService.createExecution(req.body)
Falta um `await`, porque `executionService.createExecution` retorna uma `Promise`, e ela tem que finalizar antes de mandar o resultado da requisição pro cliente:

```suggestion
    await executionService.createExecution(req.body)
```

2020-05-23 14:32 UTC, rafaelruwer commented on src/routes/executions.js
> +    res.status(200)
Tens que finalizar o request mandando o código de status pro cliente (`send`); ainda, acho que o código `201 Created` é semanticamente mais correto:

```suggestion
    res.status(201).send()
```

2020-05-23 14:32 UTC, rafaelruwer commented on src/services/ExecutionService.js
> +      await ExecutionDAO.bulkCreate(payload.executions)
Warnings do linter:
- usar uma _arrow function_, evitando `function`s não nomeadas;
- não mutar o argumento `itm`, recomendo substituir por um `map`.

```suggestion
    const executions = payload.executions.forEach((itm) => {
      return {
        ...itm,
        deviceToken: payload.deviceToken
      }
     });
      await ExecutionDAO.bulkCreate(executions)
```

2020-05-23 14:32 UTC, rafaelruwer commented on src/routes/executions.js
> +import config from "../config"
Não é usado nesse arquivo.

2020-05-23 14:35 UTC, rafaelruwer commented on src/services/index.js
> +export { default as ExecutionService } from "./ExecutionService"
Se quiser, pode deixar que o `npm run format` resolve :D

2020-05-23 22:34 UTC, rafaelruwer approved these changes

2020-05-23 22:37 UTC, merged