Feature/rota download xlsx
2020-1-DTool/backend pull request #6
Opened 2020-06-09 13:50 UTC by arczyx

# B03:Para termos um relatório com todas as métricas do hospital devemos criar uma rota e uma função para gerar e exportar o xls e mediremos o sucesso tendo um arquivo xls exportado para o usuário

Criar uma rota para baixar o xls e uma função no serviço de execuções para gerar o xls: para cada tecnologia chamar as funções do card **B01** e do **B02** para consolidar os dados e gerar um xls com a lib escolhida.

**Detalhes**
- lib escolhida para gerar o arquivo XLSX: https://www.npmjs.com/package/exceljs;
- exemplo do Excel a ser gerado em anexo.

**Autores:** João Brentano

## Checklist

- ✅ funciona conforme especificação no Postman
- 🤷‍♀️ possui testes de unidade/integração associados
- ✅ mantém cobertura de pelo menos 50%
- ✅ documentação atualizada
- ✅ código dentro dos padrões
- ✅ código sem warnings ou erros de linter
- ✅ adiciona dependências externas (✅/⚠️/❌/🤷‍♀️ aprovadas pelos AGES III)

Legenda:
- ✅: sim (funciona/builda/documentação atualizada/...)
- ⚠️: parcialmente (partes não funcionam/apenas documentação pendente/...)
- ❌: não (não builda/não funciona/não segue padrões/sem documentação/...)
- 🤷‍♀️: não se aplica (não tenho como testar/não modifica arquivos `.js`, então não precisa de linter/...)

## Outras informações

PR criado antecipadamente

2020-06-10 21:25 UTC, rafaelruwer requested changes
Roda `npm run lint` antes de submeter o PR pra verificar os problemas que o linter aponta.

Sobre a formatação, acho que não precisa bloquear esse PR pra isso. Implementa em uma branch a partir dessa e depois abre outro PR.

2020-06-10 21:25 UTC, rafaelruwer commented on src/routes/reports.js
> +    //realizadas múltiplas exportações ao mesmo tempo!
Idealmente, sim, deletar o arquivo temporário (vou ver como mandar um buffer sem ter que escrever o Excel em um arquivo, não precisa ver como deletar agora).

Colocar o ID da tecnologia no nome do arquivo, pra não ter problema de concorrência (evitar, na verdade).

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +    const ExcelJS = require("exceljs")
ExcelJS já foi importado na primeira linha do arquivo.

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +    workbook.properties.defaultColWidth = 17.14
Acho que não vale a pena definir isso pra todo o workbook, porque cada worksheet tem um padrão diferente.

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +    workbook.properties.date1904 = true
Usar o sistema de 1900, padrão do Excel (ver https://docs.microsoft.com/pt-br/office/troubleshoot/excel/1900-and-1904-date-system).

```suggestion
```

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +    workbook.lastPrinted = new Date(2016, 9, 27)
Tirar `modified` e `lastPrinted`, e ajustar as outras propriedades:

```suggestion
    workbook.creator = "dTool - AGES, PUCRS"
    workbook.lastModifiedBy = "dTool - AGES, PUCRS"
    workbook.created = new Date()
```

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +    workbook.calcProperties.fullCalcOnLoad = true
Não teremos fórmulas, não precisamos dessa linha.

```suggestion
```

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +    await workbook.xlsx.writeFile("temp.xlsx")
Adicionar ID da tecnologia no nome do arquivo sendo exportado (comentei isso na rota também).

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +        { header: "Máximo(minutos)", key: "maximumDuration", width: 50 },
Espaço antes dos parênteses:
```suggestion
        { header: "Mínimo (minutos)", key: "minimumDuration", width: 50 },
        { header: "Mediana (minutos)", key: "medianDuration", width: 50 },
        { header: "Máximo (minutos)", key: "maximumDuration", width: 50 },
```

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +      const condolidatedExecutions = workbook.addWorksheet(tech.name + " - Consolidado")
Typo: `consolidatedExecutions`.

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +      });
Já que as chaves são iguais, tu pode usar um simples `addRows`:

```suggestion
      condolidatedExecutions.addRows(exportConsolidatedExecutions)
```

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +      })
Já que as chaves são iguais, tu pode usar um simples `addRows`:

```suggestion
      executions.addRows(exportExecutions)
```

2020-06-10 21:25 UTC, rafaelruwer commented on src/services/ReportService.js
> +import { TechnologyService, ExecutionService } from "../services"
Isso gera um warning no linter, muda pra um import separado para cada arquivo:

```suggestion
import TechnologyService from "./TechnologyService"
import ExecutionService from "./ExecutionService"
```

2020-06-10 21:27 UTC, rafaelruwer submitted a review, later dismissed

2020-06-10 21:27 UTC, rafaelruwer commented on src/routes/reports.js
> +    res.download(temporaryFile)
Faltou colocar o nome do arquivo na chamada para `res.download`, como estava no código de exemplo (é importante porque será o nome do arquivo quando o usuário baixar pelo app).

2020-06-11 01:55 UTC, ghost requested changes
Favor, se possível, tentar realizar o merge com as novas features/código introduzidos pelo recente merge da B02 na branch develop

2020-06-11 23:47 UTC, arczyx commented
> Favor, se possível, tentar realizar o merge com as novas features/código introduzidos pelo recente merge da B02 na branch develop

Feito

2020-06-12 13:35 UTC, biancacamargomachado requested changes

2020-06-12 13:35 UTC, biancacamargomachado commented on src/routes/reports.js
> +    res.download(temporaryFile)
essa chamada parece duplicada, certo?
```suggestion
```

2020-06-12 13:35 UTC, biancacamargomachado commented on src/services/ReportService.js
> +    //Cria arquivo e adiciona algumas propriedades
Para evitar warnings desnecessários no lint, considere incluir espaço após os `//`
```suggestion
    // Cria arquivo e adiciona algumas propriedades
```

2020-06-12 13:35 UTC, biancacamargomachado commented on src/services/ReportService.js
> +    await workbook.xlsx.writeFile(institutionID + ".xlsx")
Para evitar warnings desnecessários no lint, cosidere fazer as concatenações desta forma:

```suggestion
    await workbook.xlsx.writeFile(`${institutionID}.xlsx`)
```

2020-06-12 14:09 UTC, biancacamargomachado approved these changes
Tem outros warnings, mas podemos arrumar isso depois...

2020-06-12 16:32 UTC, ghost approved these changes

2020-06-12 16:35 UTC, merged