BO1 - Exporta todas as execuções de atividade de uma tecnologia
2020-1-DTool/backend pull request #9
Opened 2020-06-13 14:19 UTC by ggvell

# B01 - Para ter as métricas de todas as atividades realizadas de uma tecnologia do hospital devemos ter uma função para esses cálculos e mediremos o sucesso tendo os dados calculados de todas as atividades da tecnologia

Criar uma função no serviço de execuções que exporta os dados consolidados de todas as execuções de atividade de uma tecnologia.

**Autores:** Gabriel Velloso

## Checklist

- ✅ funciona conforme especificação no Postman
- 🤷‍♀️ possui testes de unidade/integração associados
- 🤷‍♀️ mantém cobertura de pelo menos 50%
- ✅ documentação atualizada
- ✅ código dentro dos padrões
- ✅ código sem warnings ou erros de linter
- ✅ adiciona dependências externas (✅/⚠️/❌/🤷‍♀️ aprovadas pelos AGES III)

Legenda:
- ✅: sim (funciona/builda/documentação atualizada/...)
- ⚠️: parcialmente (partes não funcionam/apenas documentação pendente/...)
- ❌: não (não builda/não funciona/não segue padrões/sem documentação/...)
- 🤷‍♀️: não se aplica (não tenho como testar/não modifica arquivos `.js`, então não precisa de linter/...)

## Outras informações
Abaixo retorno através do get "{{api_url}}/reports/simple"

```
[
    {
        "activity": "Consulta",
        "role": "Médico intensivista",
        "timestamp": "2020-04-04T17:20:37.000Z",
        "duration": 1.6166666666666667,
        "deviceToken": "qwertyuiopasdfghjklzxcvbnm1234567890"
    },
    {
        "activity": "Administração de trombolítico",
        "role": "Farmaceutico",
        "timestamp": "2020-04-04T21:00:54.000Z",
        "duration": 5.433333333333334,
        "deviceToken": "qwertyuiopasdfghjklzxcvbnm1234567890"
    }
]

```

2020-06-13 22:13 UTC, rafaelruwer requested changes

2020-06-13 22:13 UTC, rafaelruwer commented on src/services/ExecutionService.js
> +    // ]
Remover comentários desnecessários.

2020-06-13 22:13 UTC, rafaelruwer commented on src/services/ExecutionService.js
>      // TODO: implementar na task B01 (https://trello.com/c/A3NnYIil)
Remover comentário desnecessário.

2020-06-13 22:27 UTC, rafaelruwer approved these changes

2020-06-14 12:38 UTC, biancacamargomachado approved these changes

2020-06-14 12:38 UTC, merged